/*
 * This source file was generated by the Gradle 'init' task
 */

import org.junit.jupiter.api.Test;

import engine.gpx.GPXReader;

import static org.junit.jupiter.api.Assertions.*;

class EngineTest {
    @Test
    void engineHasAGreeting() {
        GPXReader classUnderTest = new GPXReader();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
