/*
 * This source file was generated by the Gradle 'init' task
 */

import org.junit.jupiter.api.Test;

import engine.gpx.GPXReader;

import static org.junit.jupiter.api.Assertions.*;

class MarkerManagerTest {
    @Test
    void addMarkerTest() {
    }
}
