/*
 * This source file was generated by the Gradle 'init' task
 */
package gui;

import engine.gpx.GPXReader;

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}