/*
 * This source file was generated by the Gradle 'init' task
 */
package gui;

import engine.gpx.GPXReader;

public class Main {
    public static void main(String[] args) {
        GPXReader gpxReader = new GPXReader(
                "C:\\Users\\ethan\\Desktop\\java\\bike-maps\\data\\gpx-routes\\13717222076.gpx");
        gpxReader.read();
    }
}