/*
 * This source file was generated by the Gradle 'init' task
 */
package gui;

import engine.gpx.Engine;

public class Main {
    public static void main(String[] args) {
        System.out.println(new Engine().getGreeting());
    }
}